name: nf-scil PR checks
on:
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested
    branches:
      -main

# Cancel if a newer run is started
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    if: github.repository == 'scilus/nf-scil'
    uses: ./.github/workflows/checks.yml
    secrets: inherit
